### ISSUE TITLE
Lack of transparency on Rounded corners

### ISSUE THREAD

**Issue by conlank** [BlueBubblesApp/BlueBubbles-Desktop-App#120]
The corners of the app are rounded but still have a white background. 

![image](https://user-images.githubusercontent.com/1820574/103487372-d95aa780-4dd2-11eb-8688-f45ad39f9180.png)

and 
![image](https://user-images.githubusercontent.com/1820574/103487378-dfe91f00-4dd2-11eb-9716-f58a87bfd2ac.png)
for examples

I believe the issue is in https://github.com/BlueBubblesApp/BlueBubbles-Desktop-App/blob/master/src/main/main.ts#L161 as one of the examples on how to do frameless rounded corners is https://github.com/DEDaniel/electron-frameless-rounded/blob/master/main.js

**Comment by zlshames** [comment]
This should be fixed now. Looking at the code, this is what it looks like:
```
win = new BrowserWindow({
        width: 1200,
        height: 750,
        minWidth: 550,
        minHeight: 350,
        transparent: true,
        frame: withFrame,
        webPreferences: { nodeIntegration: true, webSecurity: false, enableRemoteModule: true, spellcheck: true }
    });
```

The `frame` parameter is false by default and is only true when the app is run with the `useNativeTitlebar` option enabled. Closing.
