### ISSUE TITLE
Close/Delete Button on chat is not transparent

### ISSUE THREAD

**Issue by conlank** [BlueBubblesApp/BlueBubbles-Desktop-App#121]
![image](https://user-images.githubusercontent.com/1820574/103487426-5d149400-4dd3-11eb-9fa1-1f68ff49b01c.png)

The close/delete button on the Message list is not transparent and so cuts off text even when "not visible", hovering and allowing the X to appear has no change in this text display behavior.

**Comment by zlshames** [comment]
I have removed the delete button as it's not functional right now. Will re-add back in when it is. We have to figure out what we want to do with the 'x' button. Does it soft-delete a conversation locally? Does it fully delete it? Not sure what to do yet. I created another issue to track that: https://github.com/BlueBubblesApp/BlueBubbles-Desktop-App/issues/162
