### ISSUE TITLE
BlueBubbles Preview Text in message isn't faded/Is too bold.

### ISSUE THREAD

**Issue by conlank** [BlueBubblesApp/BlueBubbles-Desktop-App#122]
![image](https://user-images.githubusercontent.com/1820574/103487453-a06f0280-4dd3-11eb-9d20-5056a84faf77.png)
is the same style as when a user is typing. 

![image](https://user-images.githubusercontent.com/1820574/103487484-d1e7ce00-4dd3-11eb-9bc5-fc8cc1380e84.png)

I believe the font should be changed so that the text is clearer. I also think that to more closely mimic other messaging apps, the style of the placeholder text should be changed to be more subtle. I understand this is your branding and do not want to feel like I am suggesting you remove it completely, just change the style enough so that the placeholder text and the text input from a user is visually distinct.

**Comment by zlshames** [comment]
Fixed. I also made it use the Light font instead of the Bold. Bold looks weird here.
