### ISSUE TITLE
[Suggestion] Change toggles in Settings to a dropdown menu

### ISSUE THREAD

**Issue by romhacks** [BlueBubblesApp/BlueBubbles-Desktop-App#127]
![image](https://user-images.githubusercontent.com/42524580/104110999-5ee6c780-52ab-11eb-84c4-df2af1a8f9cc.png)
Currently, the contact location settings are all independent toggles that only allow one to be enabled at a time. This seems like it would be better suited to be a dropdown menu, as it would save space and be less confusing.

**Comment by zlshames** [comment]
This is a good change. IMO, we need a drop down to select the following:
- Server DB
- Server VCF
- Local VCF

Then, based on the selection, show config options accordingly. For instance, for local VCF, we'd have an upload button to upload a custom VCF file. We should also include a "sync now" button
