### ISSUE TITLE
[Feature Request][Desktop Client] Hotkeys for switching conversations

### ISSUE THREAD

**Issue by supercsc** [BlueBubblesApp/BlueBubbles-Desktop-App#133]
It would be nice to be able to switch between conversations using keyboard hotkeys, so you don't have to reach for your mouse as often. I think ctrl+tab and ctrl+shift+tab would be good options, since that is what signal, telegram, and Messages on the mac use.

**Comment by zlshames** [comment]
Completed. Code is in my beta branch. The hotkeys are `Ctrl + <number 1 through 9>`. 1, corresponding to the first chat, 0, corresponding with the 10th chat.

**Comment by zlshames** [comment]
I also added a hotkey for `Ctrl + Shift + Tab` that will go to the "next" chat
