### ISSUE TITLE
Clicking on some chats makes the app window disappear/become invisible (Ubuntu 20.04 LTS)

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Desktop-App#141]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@inprince` in `#desktop-bugs`.

**Comment by CSab6482** [comment]
This happens to me on Windows too, I've only ever had it happen with issue #92

**Comment by zlshames** [comment]
This had to do with a failure to parse iOS 14 locations. If this still occurs (on the next update), let me know. Then it is something different.

**Comment by CSab6482** [comment]
LET'S GOOOOOOO
