### ISSUE TITLE
Reactions come in mirrored

### ISSUE THREAD

**Issue by waharris007** [BlueBubblesApp/BlueBubbles-Desktop-App#150]
Other people's reactions to my comments appear mirrored/flipped. See attached pic of "HA HA" appearing as "AH AH."
![bluebubble](https://user-images.githubusercontent.com/55819301/108230833-c8f25800-7106-11eb-8133-e5de9b5d03b3.png)

**Comment by zlshames** [comment]
Fixed. My beta branch.
