### ISSUE TITLE
Cannot display a message that is just a space

### ISSUE THREAD

**Issue by CSab6482** [BlueBubblesApp/BlueBubbles-Desktop-App#155]
(Copied from the SMServer ticket for convenience)
I was talking to someone and they were telling me about how something left them speechless, so they sent me a message that was just " ", which displays as a small blank blue bubble on iOS (the more spaces, the longer the bubble). This message didn't display on my Android phone with the BlueBubbles app, or any of my other iMessage forwarding apps, so I sat there confused waiting to receive a message only to check my iPhone and see that it was a blank. Of all the apps with this issue, SMServer was the only one that allowed me to send a blank, and SMServer and WebMessage both displayed a timestamp for the blank message.
![Blank BlueBubbles Desktop](https://user-images.githubusercontent.com/53708281/108304314-c418bd00-7175-11eb-91b2-bca8b38beb01.JPG)
![Blank iOS](https://user-images.githubusercontent.com/53708281/108304317-c5e28080-7175-11eb-9678-e9aace8342e9.PNG)
See issues [here](https://github.com/iandwelker/smserver/issues/90), [here](https://github.com/BlueBubblesApp/BlueBubbles-Android-App/issues/786), and [here](https://github.com/sgtaziz/WebMessage/issues/48)

**Comment by zlshames** [comment]
Closing. This is an Apple bug I believe

**Comment by CSab6482** [comment]
This is the first time I've had to escalate my bug report from you guys to Apple, lol. Anyone with iMessage on Big Sur please help me in my endeavor 🐸
