### ISSUE TITLE
When viewing the tapback details on a message that I added a tapback on in an individual chat, the other person's contact image shows

### ISSUE THREAD

**Issue by CSab6482** [BlueBubblesApp/BlueBubbles-Desktop-App#156]
It displays properly in group chats. Is this similar to [this issue](https://github.com/BlueBubblesApp/BlueBubbles-Android-App/issues/763)?

**Comment by zlshames** [comment]
Similar issue: https://github.com/BlueBubblesApp/BlueBubbles-Android-App/issues/763

**Comment by zlshames** [comment]
Another similar issue: https://github.com/BlueBubblesApp/BlueBubbles-Android-App/issues/873
