### ISSUE TITLE
(0.1.14 release candidate) Loading an attachment while scrolling up scrambles the attachment size numbers on different parts of the screen

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Desktop-App#170]
They fix themselves pretty quickly though

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@CSab6482` in `#desktop-bugs`.

**Comment by zlshames** [comment]
Fixed. my beta branch
