### ISSUE TITLE
(0.1.14 release candidate) Sending messages to a chat open in BB Desktop from another device [e.g. iPad] do not properly show Delivered tags

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Desktop-App#171]
Read receipts seem to sync okay though

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@CSab6482` in `#desktop-bugs`.

**Comment by CSab6482** [comment]
This might not be fixable, as seen [here](https://github.com/sgtaziz/WebMessage/issues/92)

**Comment by CSab6482** [comment]
> This works in MyMessage, I just tested it 😳

https://github.com/sgtaziz/WebMessage/issues/92#issuecomment-807705079
