### ISSUE TITLE
[RC 1.0.4] Media download message gets stretched down screen

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Desktop-App#179]
When an image or video is downloading, the 'Rendering full attachment' message is stretched down 1 character per line on the latest RC 1.0.4 https://ibb.co/PM5c4Ch

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@radeon` in `#desktop-bugs`.

**Comment by zlshames** [comment]
Fixed. my beta branch
