### ISSUE TITLE
Feature request for contact photos in notifications

### ISSUE THREAD

**Issue by CSab6482** [BlueBubblesApp/BlueBubbles-Desktop-App#188]
![chocolate1](https://user-images.githubusercontent.com/53708281/111105661-d940fb80-8529-11eb-807f-da0f3159b496.png)
![chocolate 2](https://user-images.githubusercontent.com/53708281/111105666-db0abf00-8529-11eb-8b87-8f256c3afe17.png)
There is BlueBubbles on the top, and WebMessage on the bottom. Also, a quick mention to issue #123 and my [original WebMessage feature request](https://github.com/sgtaziz/WebMessage/issues/110)

**Comment by CSab6482** [comment]
Does this work on the macOS and Linux clients?

**Comment by zlshames** [comment]
If it doesn't, we can open a new ticket
