### ISSUE TITLE
Server and Client Setup Details

### ISSUE THREAD

**Issue by chernas** [BlueBubblesApp/BlueBubbles-Desktop-App#190]
I setup the server and client seemingly fine.  I'm receiving messages when they came in, but I can't send messages from the client (Windows).  If i send the message from my iPhone, they show up in the client, but the client ones aren't getting out.

**Comment by chernas** [comment]
This is not a new chat, this is responding to an existing thread.

**Comment by zlshames** [comment]
> This is not a new chat, this is responding to an existing thread.

Did you receive any errors on your server when sending the message? Or does the message seemingly never get to the server? Mind checking your server logs?

**Comment by chernas** [comment]
I’m good, had a few pop ups to acknowledge but I couldn’t see them because I had an external monitor and they were showing on the other screen that was being used by my pc.

C

**Comment by zlshames** [comment]
> I’m good, had a few pop ups to acknowledge but I couldn’t see them because I had an external monitor and they were showing on the other screen that was being used by my pc. C
> […](#)
> On Mar 20, 2021, at 3:28 PM, Zach Shames ***@***.***> wrote: ﻿ This is not a new chat, this is responding to an existing thread. Did you receive any errors on your server when sending the message? Or does the message seemingly never get to the server? Mind checking your server logs? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Fair enough. Closing.
