### ISSUE TITLE
Contact names with accented letters do not display correctly

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Desktop-App#191]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#desktop-bugs`.

**Comment by CSab6482** [comment]
Is this a duplicate of issue #130?

**Comment by zlshames** [comment]
> Is this a duplicate of issue #130?

Maybe? Might be a VCF issue or maybe just bad parsing
