### ISSUE TITLE
Chat history gets mixed up when scrolling up (1.0.4 rc)

### ISSUE THREAD

**Issue by CSab6482** [BlueBubblesApp/BlueBubbles-Desktop-App#194]
![Loading BB Desktop](https://user-images.githubusercontent.com/53708281/111246154-27163c00-85dc-11eb-8ce3-c26afbcf2b73.png)
First I was scrolling up to see my chat history in the Ch group chat, and then I switched to an individual chat with L. However, scrolling up in L's chat still showed Ch's chat name, and L's name also showed up above one of my messages in the top right

**Comment by zlshames** [comment]
errrr, not sure why this would happen. I guess just a race case maybe? Not entirely sure how to fix it at this point

**Comment by CSab6482** [comment]
I'll do some more testing to see if the behavior repeats itself, and if not I'll close the issue 👍. I'll report back with any patterns and such too if those are there

**Comment by CSab6482** [comment]
The behavior is consistent for me. Here I performed the same test with P and L. P's contact card is an email while L's is a phone number. I know that the yellow syncing light is on, but this happened even after the sync was finished.
![still broken](https://user-images.githubusercontent.com/53708281/111925088-c1173200-8a7d-11eb-89ec-aeb1ec8d2a9f.png)

**Comment by ttay24** [comment]
@CSab6482 what are the exact steps to reproduce this? Something like:
1. Open a conversation
2. Scroll to top to load new messages and get spinner 
3. Click to open a different conversation before loading in step 2 completes 

?

**Comment by CSab6482** [comment]
> @CSab6482 what are the exact steps to reproduce this? Something like:
> 
> 1. Open a conversation
> 2. Scroll to top to load new messages and get spinner
> 3. Click to open a different conversation before loading in step 2 completes
> 
> ?

I just ran a test, and I think it only needs step 1 and 3
