### ISSUE TITLE
Chat scroll bar and resize window interfere with each other on Windows

### ISSUE THREAD

**Issue by CSab6482** [BlueBubblesApp/BlueBubbles-Desktop-App#195]
When using the macOS theme and title bar, I cannot use the scroll bar to move in a chat because my cursor automatically switches to the horizontal line for resizing. Switching to the native title bar fixes this, however, sometimes I get locked out of resizing with the native title bar.

**Comment by zlshames** [comment]
I'm not sure how much we can do about this.

**Comment by CSab6482** [comment]
Alright ¯\\_(ツ)_/¯. Closed #182
