### ISSUE TITLE
When I highlight a message and copy, only a period enters my clipboard

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Desktop-App#204]
Also it is really hard to highlight messages for copying because the reaction menu like to pop up

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@Nolan` in `#desktop-bugs`.

**Comment by CSab6482** [comment]
Kind of related https://github.com/sgtaziz/WebMessage/issues/105
